Cloud Awareness for download.py
APL-HTM-S3-AWARE/pyspedas pull request #7
Opened 2024-07-29 19:53 UTC by edmondb

Changes include Cloud Awareness for the majority of PySPEDAS that called pyspedas/utilities/download.py using the fsspec filesystem protocol (includes AWS S3 and GCS support) for URIs. The proposed changes do not break current API usage and includes the following functionality:

- Retrieve from http/https servers and place onto local URI-path data storage.
- Read/Stream from URI storage whether given as remote or local.
- Update local URI-path storage from separate remote URI-path storage.
- Allow a user to download from a remote URI (NOT RECOMMENDED) by using the `force_download` option.
- Attempt to read/stream from local storage (posix or URI-based) if the remote download/stream fails.

__Note:__ In order to make a "clean" PR, package dependencies (`fsspec`, `s3fs`, and `aioboto3`) were not included but will be in a subsequent PR for inclusion into requirements.txt and setup.py.

This code was tested using AWS' CLI on an EC2 resource provided by the HelioCloud project. Details for AWS CLI setup and temporary credential management not included, but available.

Closes https://github.com/APL-HTM-S3-AWARE/issues/issues/4

2024-07-30 20:17 UTC, vtoyedens approved these changes
I am leaving it up to Wenli to verify that functionality works on actual data, but it looks good to me

2024-07-30 22:14 UTC, wmoapl requested changes
Looks good Brent. I found one bug which we should fix. After that we're good to put in the PR.

This is the code that triggered the bug:
```
# SPEDAS_DATA_DIR=s3://helio-dh-data/wenlimo/s3test`
import pyspedas

start = '2014-11-5'
end = '2014-11-6'
omni_data = pyspedas.omni.data(trange=[start,end], no_update=True)
```
The file exists in the s3 SPEDAS_DATA_DIR but the code cannot find those files.

2024-07-30 22:14 UTC, wmoapl commented on pyspedas/utilities/download.py
> +                    matching_files = list(filter(lambda f: local in f, fs.find(local_path_to_search)))
This line does not work. `local` usually contains wildcard characters like "??" that are not recognized by `filter`. 

I think we should keep the original code: `matching_files = fnmatch.filter(filenames, local)` with either modification:
- add `*/` to the front of the pattern for `local` (e.g., "omni_hro2_1min_20141101_v??.cdf" --> "*/omni_hro2_1min_20141101_v??.cdf")
OR
- only return the actual file name instead of the entire s3 key name for `filenames` (`['helio-dh-data/wenlimo/s3test/omni/hro2_1min/2014/omni_hro2_1min_20141101_v01.cdf'] --> ['omni_hro2_1min_20141101_v01.cdf']`).

2024-07-31 01:27 UTC, edmondb commented on pyspedas/utilities/download.py
> +                    matching_files = list(filter(lambda f: local in f, fs.find(local_path_to_search)))
The issue with this is that fnmatch is primarily a Unix-based filename pattern matching package. I've instead created a better logic flow for traversing directories similar to the Unix `os.walk` but using fsspec's built-in function `fs.walk` instead.

2024-07-31 13:50 UTC, wmoapl commented on pyspedas/utilities/download.py
> +                    matching_files = list(filter(lambda f: local in f, fs.find(local_path_to_search)))
👍

2024-07-31 13:52 UTC, wmoapl commented on pyspedas/utilities/download.py
> +                    logging.info("Streaming from local URI (download-failed): " + temp_out[-1])
Can we just remove the "download-failed" part of the log? It's a bit confusing if it's just streaming from local.

2024-07-31 13:52 UTC, wmoapl approved these changes
Thanks Brent. One last small request and we're good to go 🥳

2024-07-31 17:54 UTC, merged